name: Build

on:
  push:
    branches:
      - master

# Defaults for every job and step in this workflow
defaults:
  run:
    shell: bash # Run everything using bash


jobs:
  build:
    name: Build Arch Linux Package
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:

      - name: Prepare Environment
        run: |
          useradd -m -U -s /bin/bash user -p user
          echo 'user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          pacman -Syu pacman-contrib git --noconfirm
          sed 's,#en_US,en_US,g;s,#zh_TW,zh_TW,g' -i /etc/locale.gen
          locale-gen
          echo 'en_US.UTF-8' > /etc/locale.conf

      # Check out master
      - name: Clone repository (master branch)
        uses: actions/checkout@v2
        with:
          ref: 'master'

    - name: Build Arch Linux Package
      run: |
        chmod 777 ${PWD}
        MAKEFLAGS="-j$(($(nproc)+1))" sudo -u user -EHn makepkg -sCf --noconfirm

      # Cache package
      - name: Cache installers
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./zettlr-*.zst


  prepare_release:
    name: Prepare release draft
    # Make sure (and wait until) the builds have succeeded
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Make release directory
        run: mkdir ./release

      - name: Retrieve Linux installers
        uses: actions/download-artifact@v2
        with:
          path: ./release
      # Now we are set, we have all five release assets on the VM. It's time to
      # create the SHA-checksums file and then upload everything!
      - name: Generate SHA256 checksums
        run: |
          cd ./release
          sha256sum "$(ls .)" > "SHA256SUMS.txt"
          cd ..
      - name: Verify checksums
        run: |
          cd ./release
          sha256sum -c SHA256SUMS.txt
          cd ..
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Populate the inputs of the release we already know
          name: Release Zettlr
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          draft: true # Always create as draft, so that we can populate the remaining values easily
          # Gosh, is that convenient as opposed to earlier!
          files: |
            ./release/zettlr*.zst
            ./release/SHA256SUMS.txt
