name: Build

on: push

jobs:
  build:
    name: Build Arch Linux Package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: archlinux:base-devel
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    outputs:
      pkgname: ${{ steps.metadata.outputs.pkgname }}
      pkgver: ${{ steps.metadata.outputs.pkgver }}
      pkgrel: ${{ steps.metadata.outputs.pkgrel }}
    steps:
      - name: Prepare Environment
        run: |
          useradd -m -U -s /bin/bash user -p user
          echo 'user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          pacman -Syu pacman-contrib git --noconfirm
          sed 's,#en_US,en_US,g;s,#zh_TW,zh_TW,g' -i /etc/locale.gen
          locale-gen
          echo 'en_US.UTF-8' > /etc/locale.conf

      # Check out master
      - name: Clone repository (master branch)
        uses: actions/checkout@v2

      - name: Build Arch Linux Package
        id: metadata
        run: |
          chmod 777 ${PWD}
          source ${PWD}/PKGBUILD
          echo "::set-output name=pkgname::$pkgname"
          echo "::set-output name=pkgver::$pkgver"
          echo "::set-output name=pkgrel::$pkgrel"
          MAKEFLAGS="-j$(($(nproc)+1))" sudo -u user -EHn makepkg -sCf --noconfirm

      # Cache package
      - name: Cache package
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./zettlr-*.zst

  prepare_release:
    name: Prepare release draft
    # Make sure (and wait until) the builds have succeeded
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve cached package
        uses: actions/download-artifact@v2
        with:
          path: ./
      - name: Generate SHA256 checksums
        run: |
          sha256sum ${{needs.build.outputs.pkgname}}-${{needs.build.outputs.pkgver}}-${{needs.build.outputs.pkgrel}}-x86_64.pkg.tar.zst > "SHA256SUMS.txt"
        working-directory: ./artifact
      - name: Verify checksums
        run: |
          sha256sum -c SHA256SUMS.txt
        working-directory: ./artifact
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Populate the inputs of the release we already know
          name: Release Zettlr
          body: If you can read this, we have forgotten to fill in the changelog. Sorry!
          draft: true # Always create as draft, so that we can populate the remaining values easily
          # Gosh, is that convenient as opposed to earlier!
          files: |
            ./artifact/${{needs.build.outputs.pkgname}}-${{needs.build.outputs.pkgver}}-${{needs.build.outputs.pkgrel}}-x86_64.pkg.tar.zst
            ./artifact/SHA256SUMS.txt
